#Test against this version of Node.js environment
environment:
  matrix:
  #node.js
  - nodejs_version: "6"

#install  scripts (runs aster repo cloning)
install:
  #Get the latest stable version of node.js or o.js
  - ps:install-Product node $env:node.js_version
  #- ps: $env:UWU_VERSION=git describe --tags --always --dirty
  #- ps: go build -o uwunote.exe -ldflags "-H windowsgui -X github.com/UwUNote/uwunote/internal/updates.AppVersion=$env:UWU_VERSION"
  #install modules
  - npm install

#post-install test scripts
test_script:
  #output useful info for debugging
  - node --version
  - npm --version

  #run tests
  - npm test

#dont actually build
build: off